name: crossbow_backend
description: The backend library for the Crossbow game engine.
version: 0.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  dart_sdl: ^0.10.1
  dart_style: ^2.2.5
  dart_synthizer: ^0.11.2
  drift: ^2.6.0
  jinja: ^0.4.2
  json_annotation: ^4.8.1
  logging: ^1.1.1
  meta: ^1.9.0
  open_url: ^2.0.0
  path: ^1.8.3
  plain_optional: ^1.0.0
  pubspec_yaml: ^3.1.0
  recase: ^4.1.0
  sqlite3: ^1.9.3
  ziggurat: ^0.61.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.0
  drift_dev: ^2.6.0
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.24.0
executables:
  run-game: run_game
  build-game: build_game
