name: crossbow
description: The loaded game engine

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  backstreets_widgets: ^0.6.0
  cupertino_icons: ^1.0.2
  dart_sdl: ^0.10.1
  dart_synthizer: ^0.11.1
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  intl: ^0.18.0
  json_annotation: ^4.8.0
  path: ^1.8.3
  path_provider: ^2.0.12
  recase: ^4.1.0
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  uuid: ^3.0.7
  ziggurat: ^0.55.0
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
