name: crossbow
description: The loaded game engine

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  backstreets_widgets: ^0.6.0
  crossbow_backend:
    path: ../crossbow_backend
  cupertino_icons: ^1.0.2
  dart_sdl: ^0.10.1
  dart_style: ^2.3.1
  dart_synthizer: ^0.11.1
  file_picker: ^5.2.5
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  path: ^1.8.3
  path_provider: ^2.0.14
  shared_preferences: ^2.0.20
  sqlite3: ^1.10.1
  sqlite3_flutter_libs: ^0.5.12
  url_launcher: ^6.1.10
  ziggurat: ^0.60.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
